package mnj.ont.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 01 19:23:56 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustMnjOntBomHeaderViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CustMnjOntBomHeaderViewImpl() {
    }


    /**
     * Returns the variable value for pBomNo.
     * @return variable value for pBomNo
     */
    public String getpBomNo() {
        return (String)ensureVariableManager().getVariableValue("pBomNo");
    }

    /**
     * Sets <code>value</code> for variable pBomNo.
     * @param value value to bind as pBomNo
     */
    public void setpBomNo(String value) {
        ensureVariableManager().setVariableValue("pBomNo", value);
    }

    /**
     * Returns the variable value for p_style.
     * @return variable value for p_style
     */
    public String getp_style() {
        return (String)ensureVariableManager().getVariableValue("p_style");
    }

    /**
     * Sets <code>value</code> for variable p_style.
     * @param value value to bind as p_style
     */
    public void setp_style(String value) {
        ensureVariableManager().setVariableValue("p_style", value);
    }


}
